---
app:
  configversion: "1.0"
  service:
    port: 8084
    host: "0.0.0.0"

database:
  type: "sqlite3"
  filepath: "/media/local/storage/Workspace/bbva/src/io.ml.challenges/io.ml.challenges.books-wishlist/cmd/mlbwlist/mlbwlist.db"

gsuite:
  api: "http://localhost"
